### PR TITLE
Add github actions script for auto-deployment 

### PR DESCRIPTION
**Pull request by pblottiere**

### CODE REVIEW

**Comment by pblottiere** [comment]
@SrNetoChan @elpaso What do you think? Can I merge? I added public/private deployment keys and with this PR it should be sufficient for auto-deployment.

**Comment by elpaso** [comment]
Looks good thank you!
What is the new workflow?
Say I wanted to add a new blog post, do I need to make a PR and then merge into master and it gets online automaticallly?

**Comment by pblottiere** [comment]
> Say I wanted to add a new blog post, do I need to make a PR and then merge into master and it gets online automaticallly?

In theory, the website should be automatically built as soon as a commit is pushed to `master` branch (direct push or merged PR).

**Comment by pblottiere** [comment]
Everything seems OK: https://github.com/qcooperative/website/runs/422084269?check_suite_focus=true

**Comment by elpaso** [comment]
@pblottiere the website is offline though ...

**Comment by pblottiere** [comment]
Yes I just saw that... The auto-deployment works but the content of the merge doesn't seem good... I'm reverting the commit on the `gh-pages` branch.

**Comment by pblottiere** [comment]
Website is back. I'm taking a look to understand why the result of the Hugo build is incorrect.

**Pull request merged**
